---
- name: Install Grafana
  hosts: main
  become: true

  tasks:
    - name: Download apt key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: Add grafana repo to source list
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: present
    - name: Update apt cache and install grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: true
        state: present
    - name: Ensure grafana is running and enabled
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true
