---
- name: Bootstrap Java 17
  hosts: main
  become: true

  tasks:
  - name: Install Java 17
    ansible.builtin.apt:
      name: openjdk-17-jdk
      state: present
      update_cache: true
  - name: Set Java 17 as default
    community.general.system.alternatives:
      name: java
      link: /usr/bin/java
      path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      priority: 1700
      state: present
