---
- name: Bootstrap Jenkins
  hosts: main
  become: true

  tasks:
  - name: Download apt key
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
  - name: Add apt repository
    ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
      state: present
  - name: Install Jenkins and update apt cache
    ansible.builtin.apt:
      name: jenkins
      state: present
      update_cache: true
  - name: Start Jenkins and enable it
    ansible.builtin.systemd:
      name: jenkins
      state: started
      enabled: true
