---
- name: Bootstrap Main Node
  hosts: main
  become: true
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090

  tasks:
    - name: Download apt key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: Add grafana repo to source list
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: present
    - name: Update apt cache and install grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: true
        state: present
    - name: Ensure grafana is running and enabled
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true
    - name: Download Prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.40.0-rc.0/prometheus-2.40.0-rc.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz
        mode: 0755
    - name: Extract Prometheus Resources
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: true
    - name: Create Prometheus Group
      ansible.builtin.group:
        name: prometheus
        state: present
    - name: Create Prometheus User
      ansible.builtin.user:
        name: prometheus
        group: prometheus
        state: present
        shell: /sbin/nologin
    - name: Create Prometheus Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        recurse: true
        mode: 0755
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/prometheus/rules
        - /etc/prometheus/rules.d
        - /etc/prometheus/files_sd
    - name: Set Prometheus Permissions
      ansible.builtin.file:
        path: /var/lib/prometheus
        owner: prometheus
        group: prometheus
        mode: 0775
    - name: Copy Prometheus Configuration
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /usr/local/bin/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: 0755
      loop:
        - /tmp/prometheus-2.40.0-rc.0.linux-amd64/prometheus
        - /tmp/prometheus-2.40.0-rc.0.linux-amd64/promtool
    - name: Copy Prometheus consoles and console_libraries
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/prometheus/
        remote_src: true
        owner: prometheus
        group: prometheus
        mode: 0755
      loop:
        - /tmp/prometheus-2.40.0-rc.0.linux-amd64/consoles/
        - /tmp/prometheus-2.40.0-rc.0.linux-amd64/console_libraries
    - name: Create Prometheus Config File
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: 0755
    - name: Create Prometheus systemd File
      ansible.builtin.template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: 0755
    - name: Ensure Prometheus is running and enabled
      ansible.builtin.systemd:
        name: prometheus
        state: started
        enabled: true
